---
abstract: 'a suite of adaptors between Message::Passing and collectd.'
author:
  - 'Tomas Doran (t0m) C<< <bobtfish@bobtfish.net> >>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Message::Passing::Collectd
name: Message-Passing-Collectd
no_index:
  directory:
    - inc
    - t
requires:
  JSON: 0
  Message::Passing: 0
  Module::Runtime: 0
  String::RewritePrefix: 0
  Try::Tiny: 0
  namespace::clean: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/suretec/Message-Passing-Collectd.git
version: 0.006
x_authority: GHENRY
